FROM ubuntu:20.04 as builder

RUN apt-get update \
  && apt-get install -y \
    build-essential \
    libssl-dev \
    libgmp-dev \
    libcurl4-openssl-dev \
    libjansson-dev \
    automake \
    zlib1g-dev \
    libnuma-dev \
  && rm -rf /var/lib/apt/lists/*

COPY . /app/
RUN cd /app/ && ./build.sh

#App
FROM ubuntu:20.04

RUN apt-get update \
  && apt-get install -y \
    libcurl4 \
    libjansson4 \
    libnuma-dev \
    kmod \
    msr-tools \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/cpuminer .
ENTRYPOINT ["./cpuminer"]
CMD ["-h"]
